apiVersion: apps/v1
kind: Deployment
metadata:
  name: RESOURCE_NAME
  namespace: kube-logging
  labels:
    app: LABEL
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LABEL
  template:
    metadata:
      labels:
        app: LABEL
    spec:
      containers:
      - name: RESOURCE_NAME
        image: docker.elastic.co/kibana/kibana:7.2.0
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
        ports:
        - containerPort: 5601
