apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: RESOURCE_NAME
  labels:
    app: LABEL
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: RESOURCE_NAME
roleRef:
  kind: ClusterRole
  name: RESOURCE_NAME
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: RESOURCE_NAME
  namespace: kube-logging
