apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: RESOURCE_NAME
  namespace: kube-logging
  labels:
    app: LABEL
spec:
  selector:
    matchLabels:
      app: LABEL
  template:
    metadata:
      labels:
        app: LABEL
    spec:
      serviceAccount: RESOURCE_NAME
      serviceAccountName: RESOURCE_NAME
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: RESOURCE_NAME
        image: fluent/fluentd-kubernetes-daemonset:v1.4.2-debian-elasticsearch-1.1
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch.kube-logging.svc.cluster.local"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENTD_SYSTEMD_CONF
            value: disable
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
#       imagePullSecrets:
#         - name: registry-cryptosky-image-registry
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
