kind: Service
apiVersion: v1
metadata:
  name: RESOURCE_NAME
  namespace: kube-logging
  labels:
    app: LABEL
spec:
  selector:
    app: RESOURCE_NAME
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node
